//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple.Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Majuscule", ReplyAction="http://tempuri.org/IService1/MajusculeResponse")]
        string Majuscule(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Majuscule", ReplyAction="http://tempuri.org/IService1/MajusculeResponse")]
        System.Threading.Tasks.Task<string> MajusculeAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Minuscule", ReplyAction="http://tempuri.org/IService1/MinusculeResponse")]
        string Minuscule(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Minuscule", ReplyAction="http://tempuri.org/IService1/MinusculeResponse")]
        System.Threading.Tasks.Task<string> MinusculeAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Simple.Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Simple.Client.ServiceReference1.IService1>, Simple.Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Majuscule(string value) {
            return base.Channel.Majuscule(value);
        }
        
        public System.Threading.Tasks.Task<string> MajusculeAsync(string value) {
            return base.Channel.MajusculeAsync(value);
        }
        
        public string Minuscule(string value) {
            return base.Channel.Minuscule(value);
        }
        
        public System.Threading.Tasks.Task<string> MinusculeAsync(string value) {
            return base.Channel.MinusculeAsync(value);
        }
    }
}
